### ISSUE TITLE
Move age-related checks (decision services) to age.dmn

### ISSUE THREAD

**Issue by prestoncabe** [prestoncabe/dmn-benefit-toolbox#19]
I think we should retire `eligibility.dmn` and put checks in DMN files that are named by topic.

- [ ] `childAgeThreeOrFourSeptFirst`
- [ ] `someoneAgeSixtyOrOlder`
- [ ] drop the now-redundant "Age" from these names (should be able to refer as `Age.childThreeOrFourSeptFirst` and `Age.someoneSixtyOrOlder`)

**Comment by sierscse** [comment]
Moving the age related decisions from the eligibility.dmn to age.dmn initially seemed to work and all tests passed when I moved them to the age.dmn folder, and remaining tests in eligibility.dmn were also passing. Once I then try to remove the old decisions from eligibility.dmn, the new age.dmn tests stop passing. I'm not sure why. 

I'm now getting this Thunder Client error and cannot run additional tests: "The free version collection run limit of 30 is reached."
