### ISSUE TITLE
Update specifications with new Low-Income Tax Freeze Rules

### ISSUE THREAD

**Issue by sierscse** [prestoncabe/dmn-benefit-toolbox#33]
This was just updated today on the Philly Department of Revenue  website:

https://www.phila.gov/services/payments-assistance-taxes/taxes/property-and-real-estate-taxes/get-real-estate-tax-relief/apply-for-the-low-income-real-estate-tax-freeze/

Basically, the Senior Tax Freeze is now all ages. Will they be phasing out the STF after this year?

**Comment by prestoncabe** [comment]
Interesting! - Great case for software like we're building, to make it easy to adapt.

**Comment by sierscse** [comment]
I also added some information about the Senior Tax Freeze, which is very similar to this new program except that seniors can back-date their eligibility up to five years if they were previously eligible in order to get a lower freeze rate. However the benefit deadline is in a few days, Sept 30, so we probably want to hold off on building it for MVP.
