### ISSUE TITLE
Add displayName for benefit names and decision checks

### ISSUE THREAD

**Issue by sierscse** [prestoncabe/dmn-benefit-toolbox#50]
- [x] Add for benefit names
- [ ] Add for decision checks per benefit

**Comment by prestoncabe** [comment]
As discussed, I'll look at this one since it is proving to be trickier than we initially assumed.

**Comment by prestoncabe** [comment]
I went back to the idea of just converting camelCase to "sentence" form ("Camel Case").  AI helped a lot. The FEEL inside of the form is ugly, but works.  See fc94e8642516a8459d8156b49fe8d6dbee620d40

Calling this good enough for now...

![image](https://github.com/user-attachments/assets/f4e078b1-f9a6-44c7-8d70-971f5a28bd5b)
